// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ContainerRenameReq struct {
	IdReq
	NewName string `form:"newName"`
}

type ContainerRestoreReq struct {
	Filename string `json:"filename"`
}

type ContainerUpdateReq struct {
	IdReq
	ImageNameAndTag string `form:"imageNameAndTag"`
	ContainerName   string `form:"containerName"`
}

type CreateContainerReq struct {
	OldName         string `json:"old_name"`
	NewName         string `json:"new_name"`
	ImageNameAndTag string `json:"image_name_and_tag"`
}

// ── 镜像快照 ──────────────────────────────────────────────

// ── 容器迁移 ──────────────────────────────────────────────

type MigrateTagReq struct {
	ImageID string `json:"imageId"`
	Ref     string `json:"ref"`
}

type MigrateExportReq struct {
	Containers    []string `json:"containers,optional"`
	IncludeImages bool     `json:"includeImages,optional"`
	Compress      bool     `json:"compress,optional"`
	RedactEnv     bool     `json:"redactEnv,optional"`
	LocalImages   []string `json:"localImages,optional"`
	Note          string   `json:"note,optional"`
}

type MigratePlanReq struct {
	File string `json:"file"`
}

type MigrateItemOverride struct {
	Name           string            `json:"name"`
	Skip           bool              `json:"skip,optional"`
	NewName        string            `json:"newName,optional"`
	PortMap        map[string]string `json:"portMap,optional"`
	MountMap       map[string]string `json:"mountMap,optional"`
	AutoCreateDirs bool              `json:"autoCreateDirs,optional"`
}

type MigrateApplyReq struct {
	File           string                `json:"file"`
	Items          []MigrateItemOverride `json:"items,optional"`
	Start          bool                  `json:"start,optional"`
	AutoCreateDirs bool                  `json:"autoCreateDirs,optional"`
}

type SnapshotCreateReq struct {
	ContainerName string `json:"containerName,optional"`
	ImageID       string `json:"imageId,optional"`
}

type SnapshotRollbackReq struct {
	ContainerName string `json:"containerName"`
	Ref           string `json:"ref"`
}

type SnapshotPruneReq struct {
	Keep int `json:"keep,optional"`
}

type DelContainerBackupReq struct {
	Filename string `form:"filename"`
}

type DoLoginReq struct {
	SecretKey string `form:"secret_key,optional"`
}

type GetProgressReq struct {
	TaskId string `path:"taskid"`
}

type IdReq struct {
	Id string `path:"id"`
}

type ComposeFileReq struct {
	ContainerId string `path:"id"`
}

type LoginReq struct {
	SecretKey string `form:"secretKey,optional"`
}

type MsgResp struct {
	Status string `json:"status"`
	Msg    string `json:"msg"`
}

type RemoveContainerReq struct {
	Name string `json:"name"`
}

type RemoveImageReq struct {
	IdReq
	Force bool `form:"force,default=false"`
}

type RenameContainerReq struct {
	OldName string `json:"oldName"`
	NewName string `json:"newName"`
}

type Resp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type StartContainerReq struct {
	Name string `json:"name"`
}

type StopContainerReq struct {
	Name string `json:"name"`
}

type VerifyJwtReq struct {
	Jwt string `form:"jwt,optional"`
}

type VersionMsgResp struct {
	Version   string `json:"version"`
	BuildDate string `json:"build_date"`
}

type VersionReq struct {
	Type string `form:"type"`
}

type GetNewImageReq struct {
	ImageNameAndTag string `json:"image_name_and_tag"`
}

type GroupUpdateReq struct {
	IdReq
}
