// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	accelerator "github.com/libremk66/DockHamster/internal/handler/accelerator"
	auth "github.com/libremk66/DockHamster/internal/handler/auth"
	autoupdate "github.com/libremk66/DockHamster/internal/handler/autoupdate"
	compose "github.com/libremk66/DockHamster/internal/handler/compose"
	container "github.com/libremk66/DockHamster/internal/handler/container"
	favicon "github.com/libremk66/DockHamster/internal/handler/favicon"
	icons "github.com/libremk66/DockHamster/internal/handler/icons"
	image "github.com/libremk66/DockHamster/internal/handler/image"
	migrate "github.com/libremk66/DockHamster/internal/handler/migrate"
	progress "github.com/libremk66/DockHamster/internal/handler/progress"
	selfupdate "github.com/libremk66/DockHamster/internal/handler/selfupdate"
	snapshot "github.com/libremk66/DockHamster/internal/handler/snapshot"
	version "github.com/libremk66/DockHamster/internal/handler/version"
	"github.com/libremk66/DockHamster/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: webindexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename",
				Handler: container.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/restart",
				Handler: container.RestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/start",
				Handler: container.StartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/stop",
				Handler: container.StopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/update",
				Handler: container.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup",
				Handler: container.BackupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup2compose",
				Handler: container.Backup2composeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/backups",
				Handler: container.DelRestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/backups/restore",
				Handler: container.RestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/listBackups",
				Handler: container.ListBackupsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers",
				Handler: container.ContainersListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: icons.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: icons.ObtainHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/icons"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/image/:id",
				Handler: image.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/images",
				Handler: image.ImagesListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/progress/:taskid",
				Handler: progress.GetProgressHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/autoUpdate/settings",
				Handler: autoupdate.GetSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/autoUpdate/settings",
				Handler: autoupdate.SaveSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/autoUpdate/run",
				Handler: autoupdate.RunHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/autoUpdate/check",
				Handler: autoupdate.CheckNowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/autoUpdate/check/status",
				Handler: autoupdate.CheckStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/autoUpdate/status",
				Handler: autoupdate.StatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tasks",
				Handler: autoupdate.TasksHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/autoUpdate/testNotify",
				Handler: autoupdate.TestNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/updateGroup",
				Handler: autoupdate.GroupUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/snapshot/list",
				Handler: snapshot.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/snapshot/create",
				Handler: snapshot.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/snapshot/rollback",
				Handler: snapshot.RollbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/snapshot/prune",
				Handler: snapshot.PruneHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/snapshot",
				Handler: snapshot.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/migrate/images/report",
				Handler: migrate.ImageReportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/migrate/images/tag",
				Handler: migrate.TagImageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/migrate/exports",
				Handler: migrate.ExportHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/migrate/exports",
				Handler: migrate.ListExportsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/migrate/exports/download",
				Handler: migrate.DownloadExportHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/migrate/exports",
				Handler: migrate.DeleteExportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/migrate/imports/upload",
				Handler: migrate.UploadImportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/migrate/imports/plan",
				Handler: migrate.PlanImportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/migrate/imports/apply",
				Handler: migrate.ApplyImportHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: version.VersionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/favicon/resolve",
				Handler: favicon.ResolveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/selfUpdate/status",
				Handler: selfupdate.StatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/selfUpdate/run",
				Handler: selfupdate.RunHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/accelerator/settings",
				Handler: accelerator.GetSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/accelerator/settings",
				Handler: accelerator.SaveSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/accelerator/test",
				Handler: accelerator.TestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/accelerator/pull",
				Handler: accelerator.PullHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/composefile",
				Handler: compose.ComposeFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/logs",
				Handler: compose.LogsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
